//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepoGirisCikis
    {
        public int Id { get; set; }
        public Nullable<int> FisNo { get; set; }
        public Nullable<int> DepoKodu { get; set; }
        public Nullable<int> GCMiktarı { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string KullaniciAdi { get; set; }
    }
}
